version: "3.9"
services:
  web:
    build: .
    ports:
      - "5100:5100"
    environment:
      MHCONFIG_FILE: /run/secrets/mhconfig.py
    restart: always
    secrets:
      - mhconfig.py

secrets:
  mhconfig.py:
    file: mhconfig.py
