name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build the Docker image
      uses: docker/build-push-action@v3.1.0
      with:
        context: .
        push: false
        tags: jzalger/meathook:latest
